version: '2'
services:
    wordpress:
      image: wordpress
      links:
        - db:mysql
      ports:
        - 80:80
      environment:
        WORDPRESS_DB_PASSWORD: example
            
    db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: example
